version: "1"

services:
  - type: web
    name: excaliadrw-http-server
    env: docker
    region: singapore
    plan: free
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PUBLIC_URL
        value: https://http-server-6i9s.onrender.com
      - key: PORT
        value: 3001

  - type: web
    name: excaliadrw-ws-backend
    env: docker
    region: singapore
    plan: free
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.websocket
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PUBLIC_URL
        value: https://http-server-6i9s.onrender.com
      - key: PORT
        value: 8080
