FROM node:22-alpine AS build

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npm install -g pnpm
WORKDIR /app

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml 
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml 
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json

COPY packages packages

COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install

RUN pnpm run db:generate

RUN pnpm --filter http-backend... run build

FROM node:22-alpine AS run

WORKDIR /app
RUN npm install -g pnpm

COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/pnpm-workspace.yaml ./
COPY --from=build /app/packages/DB ./packages/DB
COPY --from=build /app/apps/http-backend/package.json ./apps/http-backend/
COPY --from=build /app/apps/http-backend/dist ./apps/http-backend/dist

RUN pnpm install --frozen-lockfile
EXPOSE 3001

CMD ["sh","-c","pnpm exec --filter @repo/DB prisma migrate deploy --schema=./prisma/schema.prisma && node apps/http-backend/dist/index.js"]
