FROM node:22-alpine AS build

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npm install -g pnpm
WORKDIR /app

COPY pnpm-lock.yaml pnpm-lock.yaml 
COPY pnpm-workspace.yaml pnpm-workspace.yaml 
COPY turbo.json turbo.json
COPY package.json package.json

COPY packages packages

COPY ./apps/ws-backend ./apps/ws-backend

RUN pnpm install

RUN pnpm run db:generate

RUN pnpm --filter ws-backend... run build

FROM node:22-alpine AS run

RUN npm install -g pnpm
WORKDIR /app

COPY --from=build /app/package.json ./
COPY --from=build /app/pnpm-lock.yaml ./
COPY --from=build /app/pnpm-workspace.yaml ./
COPY --from=build /app/packages/DB ./packages/DB
COPY --from=build /app/packages/common_DB ./packages/common_DB
COPY --from=build /app/packages/common ./packages/common
COPY --from=build /app/packages/typescript-config ./packages/typescript-config
COPY --from=build /app/packages/eslint-config ./packages/eslint-config
COPY --from=build /app/apps/ws-backend/package.json ./apps/ws-backend/
COPY --from=build /app/apps/ws-backend/dist ./apps/ws-backend/dist

RUN pnpm install --frozen-lockfile
EXPOSE 8080

CMD ["sh", "-c","pnpm --filter @repo/DB run migrate && node apps/ws-backend/dist/index.js"]